to support manufacturing test

diff --git a/target/linux/ramips/base-files/usr/srg/scripts/we65ac-mfginfo-cli b/target/linux/ramips/base-files/usr/srg/scripts/we65ac-mfginfo-cli
--- a/target/linux/ramips/base-files/usr/srg/scripts/we65ac-mfginfo-cli
+++ b/target/linux/ramips/base-files/usr/srg/scripts/we65ac-mfginfo-cli
@@ -259,14 +259,19 @@ write_mfg_info_to_flash()
 
 	if [ $ret -eq 0 ]; then
 		printf "Success!\n"
+		return 0
 	else
 		printf "Failed, cause: %d\n" "$ret"
 		printf "Device serialization failed, please report to SmartRG!\n"
 
 		return 1
 	fi
+}
 
-	# Erase factory partition so MACs get re-written at next boot if write below fails
+# Restore to factory default 
+factory_restore()
+{
+	# Erase factory partition so MACs get re-written at next boot
 	get_factory_partition
 
 	printf "Erasing factory flash partition ${FACTORY_PART}.. "
@@ -275,11 +280,8 @@ write_mfg_info_to_flash()
 	ret=$?
 
 	if [ $ret -eq 0 ]; then
-		printf "Success!\n"
+		return 0
 
-		# save new mfginfo to /tmp or /etc then write data back to factory partition
-		/usr/srg/scripts/getmfginfo boot
-		/usr/srg/scripts/we65ac-serialize
 	elif [ $ret -ne 0 ]; then
 		printf "Failed, cause: %d\n" "$ret"
 		printf "Device serialization failed, please report to SmartRG!\n"
@@ -290,8 +292,8 @@ write_mfg_info_to_flash()
 	# erase overlay
 	/sbin/jffs2reset -y
 
-	printf "\nDevice serialization complete, rebooting.. \n"
-	
+	printf "\n"
+
 	# sync and pause before returning and exiting
 	sync
 	sleep 1
@@ -359,113 +361,278 @@ printf "#    Product: $PRODUCT                 #\n"
 printf "#                                    #\n"
 printf "######################################\n\n" 
 
+##
+
+# Get the mfg info if they are in mfg partition
+if [ -e /tmp/mfginfo.sh ]; then
+	source /tmp/mfginfo.sh
+fi
+
+SUCCESS="~!success!~"
+FAILED="~!failed!~"
+BUT_SUCCESS="~!success:"
+
 # find mfg info partition
 get_mfg_partition
-
-
-##
-# Get the base MAC
-##
-printf "Enter Base MAC Address: "
-while [ 1 ]; do
-	read TMP_MAC
-	
-	verify_mac
-	if [ $? -eq 0 ]; then
-		MFG_MAC=$TMP_MAC
-		break
-	else
-		printf "Invalid base MAC syntax; please try again\n\n"
-		printf "Enter Base MAC: "
-	fi
-done
-
-
-##
-# Get the serial number
-##
-printf "Enter Serial Number: "
-while [ 1 ]; do
-	read TMP_SN
-	
-	verify_serial
-	if [ $? -eq 0 ]; then
-		MFG_SERIAL=$TMP_SERIAL
-		MFG_MODEL=$TMP_MODEL
-		break
-	else
-		printf "Invalid serial number syntax; please try again\n\n"
-		printf "Enter Serial Number: "
-	fi
-done
-
-
-##
-# Get the hardware rev
-##
-printf "Enter Hardware Revision: "
-while [ 1 ]; do
-	read TMP_HWREV
-	
-	verify_hw_rev
-	if [ $? -eq 0 ]; then
-		MFG_HWREV=$TMP_HWREV
-		break
-	else
-		printf "Invalid hardware revision syntax; please try again\n\n"
-		printf "Enter Hardware Revision: "
-	fi
-done
-
-
-##
-# Get the engnum
-##
-printf "Enter Hardware EngNum: "
-while [ 1 ]; do
-	read TMP_ENGNUM
-	
-	verify_hw_engnum
-	if [ $? -eq 0 ]; then
-		MFG_ENGNUM=$TMP_ENGNUM
-		break
-	else
-		printf "Invalid hardware EngNum; please try again\n\n"
-		printf "Enter Hardware EngNum: "
-	fi
-done
-
 
 ##
 # Build the WPS PIN
 ##
 MFG_WPS_PIN=$(cat /dev/urandom 2>>/dev/null | tr -cd 0-9 2>>/dev/null | head -c 8)
 
+fun_led()
+{
+	CMD_PATH="/usr/bin"
+	PSID=`/bin/ps | $CMD_PATH/grep kiwi-leds | $CMD_PATH/grep -v grep | $CMD_PATH/awk '{print $1}'`
+	
+	if [ "$PSID" != "" ]; then
+		/bin/kill -9 $PSID
+	fi
 
-##
-# Print data and verify with user
-##
-print_mfg_info
+	opt=$1
+	led_name="/sys/class/leds/we65ac:range:"
 
-printf "\nWrite data to flash? (y/n) "
-read DOIT
+# turn off all LEDs
+	if [ "$opt" == "off" ]; then
+		echo none > "$led_name"01-too-far/trigger
+		echo none > "$led_name"02-too-far/trigger
+		echo none > "$led_name"03-ok/trigger
+		echo none > "$led_name"04-too-close/trigger
+		echo none > "$led_name"05-too-close/trigger
 
-case ${DOIT} in
-	[Yy]*) write_mfg_info_to_file && write_mfg_info_to_flash && NEED_REEBOOT=1 ;;
-	*) printf "\nSerialization aborted by user; flash NOT written!\n\n" ;;
-esac
+		echo 0 > "$led_name"01-too-far/brightness
+		echo 0 > "$led_name"02-too-far/brightness
+		echo 0 > "$led_name"03-ok/brightness
+		echo 0 > "$led_name"04-too-close/brightness
+		echo 0 > "$led_name"05-too-close/brightness
+
+# turn on all LED
+	elif [ "$opt" == "on" ]; then
+		echo default-on > "$led_name"01-too-far/trigger
+		echo default-on > "$led_name"02-too-far/trigger
+		echo default-on > "$led_name"03-ok/trigger
+		echo default-on > "$led_name"04-too-close/trigger
+		echo default-on > "$led_name"05-too-close/trigger
+	else
+		echo "$FAILED -invalid option"
+		return 1
+	fi	
+	echo "$SUCCESS"
+}
+
+fun_button()
+{
+	opt=$1
+
+	BTN_PATH="/etc/rc.button"
+	TEST_PATH="/usr/srg/scripts"
+
+	if [ "$opt" == "ban" ]; then
+		/bin/cp -f $TEST_PATH/reset $BTN_PATH/reset
+		/bin/cp -f $TEST_PATH/BTN_0 $BTN_PATH/BTN_0
+		/bin/cp -f $TEST_PATH/BTN_2 $BTN_PATH/BTN_2
+
+		echo "$SUCCESS"
+
+	elif [ "$opt" == "resume" ]; then
+		/bin/cp -f /rom$BTN_PATH/reset $BTN_PATH/reset
+		/bin/cp -f /rom$BTN_PATH/BTN_0 $BTN_PATH/BTN_0
+		/bin/cp -f /rom$BTN_PATH/BTN_2 $BTN_PATH/BTN_2
+
+		echo "$SUCCESS"
+
+	elif [ "$opt" == "r" ]; then
+		/bin/cp -f $TEST_PATH/reset $BTN_PATH/reset
+		/bin/cp -f $TEST_PATH/BTN_0 $BTN_PATH/BTN_0
+		/bin/cp -f $TEST_PATH/BTN_2 $BTN_PATH/BTN_2
+
+		COUNTER=0
+		PLAG_PATH="/tmp/button_flag"
+
+		while [ $COUNTER -lt 9 ]; do
+#			echo the counter is $COUNTER
+			let COUNTER=COUNTER+1
+			/bin/sleep 1
+
+			var=""
+			if [ -f $PLAG_PATH/reset ]; then
+				var="reset"
+			elif [ -f $PLAG_PATH/wps ]; then 
+				var="wps"
+			elif [ -f $PLAG_PATH/unlock ]; then 
+				var="unlock"
+			elif [ -f $PLAG_PATH/lock ]; then 
+				var="lock"
+			fi
+
+#			echo $var
+			if [ "$var" != "" ]; then
+				echo $BUT_SUCCESS$var"!~"
+				/bin/rm -rf $PLAG_PATH
+				return 1
+			fi
+
+			if [ $COUNTER -ge 9 ]; then
+				echo "$FAILED"
+			fi			
+		done
+	else 
+		echo "$FAILED -invalid option"
+	fi
+
+}
+
+fun_cmd_list()
+{
+	echo "mfg-set mac xx:xx:xx:xx:xx:xx"
+	echo "mfg-set sn <value>"
+	echo "mfg-set hwrev <value>"
+	echo "mfg-set engnum <value>"
+
+	echo "mfg-get mac"
+	echo "mfg-get sn"
+	echo "mfg-get hwrev"
+	echo "mfg-get engnum"
+
+	echo "mfg-cmd led [on/off]"
+	echo "mfg-cmd button [ban/resume/r]"
+	echo "mfg-cmd mfgblock"
+	echo "mfg-cmd mfglist"
+	echo "mfg-cmd restore"
+}
+
+fun_mfg_get()
+{
+	opt=$1
+
+	if [ "$opt" == "mac" ]; then
+		echo ~!"${MFG_MAC}"!~
+
+ 	elif [ "$opt" == "sn" ]; then
+		echo ~!"${MFG_MODEL}-${MFG_SERIAL}"!~
+
+	elif [ "$opt" == "hwrev" ]; then
+		echo ~!"${MFG_HWREV}"!~
+
+	elif [ "$opt" == "engnum" ]; then
+		echo ~!"${MFG_ENGNUM}"!~
+
+	else
+		echo "failed -invalid option"
+	fi
+}
+
+fun_mfg_set()
+{
+	opt=$1
+
+	if [ "$opt" == "mac" ]; then
+		TMP_MAC=$2
+	
+		verify_mac
+		if [ $? -eq 0 ]; then
+			MFG_MAC=$TMP_MAC
+			echo "$SUCCESS"
+		else
+			echo "$FAILED"
+		fi
+
+	elif [ "$opt" == "sn" ]; then
+		TMP_SN=$2
+	
+		verify_serial
+		if [ $? -eq 0 ]; then
+			MFG_SERIAL=$TMP_SERIAL
+			MFG_MODEL=$TMP_MODEL
+			echo "$SUCCESS"
+		else
+			echo "$FAILED"
+		fi
+
+	elif [ "$opt" == "hwrev" ]; then
+		TMP_HWREV=$2
+	
+		verify_hw_rev
+		if [ $? -eq 0 ]; then
+			MFG_HWREV=$TMP_HWREV
+			echo "$SUCCESS"
+		else
+			echo "$FAILED"
+		fi
+
+	elif [ "$opt" == "engnum" ]; then
+		TMP_ENGNUM=$2
+
+		verify_hw_engnum
+		if [ $? -eq 0 ]; then
+			MFG_ENGNUM=$TMP_ENGNUM
+			echo "$SUCCESS"
+		else
+			echo "$FAILED"
+		fi
+
+	else
+		echo "failed -invalid option"
+	fi
+}
 
 
-##
-# Verify reboot with the user if needed
-##
-printf "\nPerform reboot to complete changes? (y/n) "
-read DOIT
+fun_mfg_cmd()
+{
+	opt=$1
 
-case ${DOIT} in
-	[Yy]*) printf "\n\nRebooting NOW!!\n\n"; sleep 1; reboot ;;
-	*) printf "\nNot rebooting per user request\n" ;;
-esac
+	if [ "$opt" == "led" ]; then
+		fun_led $2;
+	elif [ "$opt" == "button" ]; then
+		fun_button $2;
+	elif [ "$opt" == "mfgblock" ]; then
+		write_mfg_info_to_file
+		write_mfg_info_to_flash
+
+		if [ $? -eq 0 ]; then
+			echo "$SUCCESS"
+		else
+			echo "$FAILED"
+		fi
+
+ 	elif [ "$opt" == "restore" ]; then
+		factory_restore
+
+		if [ $? -eq 0 ]; then
+			echo "$SUCCESS"
+		else
+			echo "$FAILED"
+		fi
+
+	elif [ "$opt" == "mfglist" ]; then
+		print_mfg_info
+
+	else
+		echo "failed -invalid option"
+	fi
+}
+
+
+while true; do
+
+	read -p "#" CMD OPT P1 P2 P3
+
+	if [ "$CMD" == "help" ]; then
+		fun_cmd_list;
+
+ 	elif [ "$CMD" == "mfg-set" ]; then
+		fun_mfg_set $OPT $P1;
+
+	elif [ "$CMD" == "mfg-get" ]; then
+		fun_mfg_get $OPT;
+
+	elif [ "$CMD" == "mfg-cmd" ]; then
+		fun_mfg_cmd $OPT $P1;
+
+	else
+		echo "failed: -invalid command"
+	fi	
+done
 
 
 ##
